<a href="https://colab.research.google.com/github/ElaYJ/Study_Deep_Learning/blob/main/Framework/PyTorch/19_%ED%85%90%EC%84%9C%20%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서 연산

In [1]:
import torch

### 기본 연산

In [2]:
x = torch.arange(0, 5)
y = torch.arange(1, 6)

In [3]:
print(x, y, end='\n')

tensor([0, 1, 2, 3, 4]) tensor([1, 2, 3, 4, 5])


In [4]:
print(x + y)
print(torch.add(x, y))
print(x.add(y))

tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])


In [5]:
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([-1, -1, -1, -1, -1])
tensor([-1, -1, -1, -1, -1])
tensor([-1, -1, -1, -1, -1])


In [6]:
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([ 0,  2,  6, 12, 20])
tensor([ 0,  2,  6, 12, 20])
tensor([ 0,  2,  6, 12, 20])


In [7]:
print(x / y)
print(torch.div(x, y))
print(x.div(y))

tensor([0.0000, 0.5000, 0.6667, 0.7500, 0.8000])
tensor([0.0000, 0.5000, 0.6667, 0.7500, 0.8000])
tensor([0.0000, 0.5000, 0.6667, 0.7500, 0.8000])


In [8]:
print(x**y)
print(torch.pow(x, y))
print(x.pow(y))

tensor([   0,    1,    8,   81, 1024])
tensor([   0,    1,    8,   81, 1024])
tensor([   0,    1,    8,   81, 1024])


In [9]:
print(-x)
print(torch.negative(x))
print(x.negative())

tensor([ 0, -1, -2, -3, -4])
tensor([ 0, -1, -2, -3, -4])
tensor([ 0, -1, -2, -3, -4])


* `torch.abs`: 절대값
* `torch.sign`: 부호
* `torch.round`: 반올림
* `torch.ceil`: 올림
* `torch.floor`: 내림
* `torch.square`: 제곱
* `torch.sqrt`: 제곱근
* `torch.maximum`: 두 텐서의 각 원소에서 최댓값만 반환.
* `torch.minimum`: 두 텐서의 각 원소에서 최솟값만 반환.
* `torch.cumsum`: 누적합
* `torch.cumprod`: 누적곱


In [10]:
print(torch.abs)
print(torch.sign)
print(torch.round)
print(torch.ceil)
print(torch.floor)
print(torch.square)
print(torch.sqrt)
print(torch.maximum)
print(torch.minimum)
print(torch.cumsum)
print(torch.cumprod)

<built-in method abs of type object at 0x797a27a85840>
<built-in method sign of type object at 0x797a27a85840>
<built-in method round of type object at 0x797a27a85840>
<built-in method ceil of type object at 0x797a27a85840>
<built-in method floor of type object at 0x797a27a85840>
<built-in method square of type object at 0x797a27a85840>
<built-in method sqrt of type object at 0x797a27a85840>
<built-in method maximum of type object at 0x797a27a85840>
<built-in method minimum of type object at 0x797a27a85840>
<built-in method cumsum of type object at 0x797a27a85840>
<built-in method cumprod of type object at 0x797a27a85840>


#### 차원 축소 연산
PyTorch는 기본이 reduce 연산

In [11]:
x = torch.randint(10, size=(5, 2, 4))
print(x.shape)
print(x)

torch.Size([5, 2, 4])
tensor([[[1, 9, 7, 4],
         [1, 8, 6, 6]],

        [[2, 9, 8, 8],
         [6, 3, 6, 7]],

        [[2, 5, 8, 3],
         [8, 1, 9, 1]],

        [[5, 1, 8, 4],
         [7, 6, 7, 2]],

        [[4, 9, 0, 4],
         [7, 6, 3, 8]]])


In [12]:
print(torch.sum(x))
print(torch.sum(x).shape)
print(torch.sum(x, dim=1))
print(torch.sum(x, dim=1).shape)
print(torch.sum(x, dim=2))
print(torch.sum(x, dim=2).shape)

tensor(209)
torch.Size([])
tensor([[ 2, 17, 13, 10],
        [ 8, 12, 14, 15],
        [10,  6, 17,  4],
        [12,  7, 15,  6],
        [11, 15,  3, 12]])
torch.Size([5, 4])
tensor([[21, 21],
        [27, 22],
        [18, 19],
        [18, 22],
        [17, 24]])
torch.Size([5, 2])


#### 행렬 연산

In [13]:
a = torch.tensor([[2, 0], [0, 1]], dtype=torch.float32)
b = torch.tensor([[1, 1], [1, 1]], dtype=torch.float32)
a, b

(tensor([[2., 0.],
         [0., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [14]:
torch.matmul(a, b), torch.mm(a, b)

(tensor([[2., 2.],
         [1., 1.]]),
 tensor([[2., 2.],
         [1., 1.]]))

In [15]:
torch.linalg.inv(a)

tensor([[0.5000, 0.0000],
        [0.0000, 1.0000]])

### 크기와 차원을 바꾸는 명령

 - `torch.reshape`
 - `tensor.view`
 - `torch.transpose`

In [16]:
# view  함수는 이렇게 못씀
torch.view(a, (4, -1))

AttributeError: module 'torch' has no attribute 'view'

In [18]:
a

tensor([[2., 0.],
        [0., 1.]])

In [17]:
print(a.view(4, -1), a.view((4, -1)), sep="\n")
print(a.view(4, -1).shape, a.view((4, -1)).shape)

tensor([[2.],
        [0.],
        [0.],
        [1.]])
tensor([[2.],
        [0.],
        [0.],
        [1.]])
torch.Size([4, 1]) torch.Size([4, 1])


In [19]:
torch.reshape(a, (4, -1))

tensor([[2.],
        [0.],
        [0.],
        [1.]])

In [20]:
# view 함수가 있어 expand_dims 같은 함수가 따로 필요없다.
a.view((1, 4, 1)), a.view((1, 4, 1)).shape

(tensor([[[2.],
          [0.],
          [0.],
          [1.]]]),
 torch.Size([1, 4, 1]))

In [21]:
print(torch.squeeze(a.view((1, 4, 1)), dim=2))
print(torch.squeeze(a.view((1, 4, 1)), dim=2).shape)

tensor([[2., 0., 0., 1.]])
torch.Size([1, 4])


expand_dims 함수 대신에 unsqueeze 함수가 있다.

In [22]:
print(torch.unsqueeze(a.view((1, 4)), dim=2))
print(torch.unsqueeze(a.view((1, 4)), dim=2).shape)

tensor([[[2.],
         [0.],
         [0.],
         [1.]]])
torch.Size([1, 4, 1])


##### 여러 함수가 torch.명령어 형태, tensor.명령어 로  사용 할 수 있다.

In [23]:
a = torch.arange(10).view(5, 2)

In [24]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [25]:
a.transpose(1, 0) #--> dim0=0, dim1=1

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

In [26]:
torch.transpose(a, 1, 0)

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

#### 함수 끝에 `_`를 붙이면 inplace명령이 된다.(안되는 함수가 존재함)

In [27]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [28]:
print(a)
print(a.transpose_(0, 1)) #--> dim0=0, dim1=1
print(a)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])


In [29]:
a.shape

torch.Size([2, 5])

In [30]:
a

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

In [ ]:
print(a.view(-1, 1), a.view(-1, 1).shape)

### transpose 하고 view  했을 때 이런 에러가 발생하기도 한다.

<img src="https://github.com/ElaYJ/supplement/assets/153154981/649c25c2-cadf-4660-a68e-dbbc55f0ae2b" width="57%">


이는 PyTorch가 데이터를 메모리에 저장하는 방식과 view, reshape, transpose 연산들이 연산을 수행하는 방식의 차이에 기인한다.
메모리상의 데이터의 물리적 위치와 index가 일치 할 때 contiguous(인접\[접촉]하고 있는) 하다고 표현하는데, view는 contiguous해야만 연산을 수행할 수 있다.

이를 해결하기위해 tensor.contiguous() 함수를 호출하여 데이터를 정리해주면 된다. 근데! 이런 이슈는 가끔 나오는 거니 어려우면 지금은 그냥 넘어가도 좋다!!!!

In [33]:
a = a.contiguous()
print(a.view(-1, 1), a.view(-1, 1).shape)

tensor([[0],
        [2],
        [4],
        [6],
        [8],
        [1],
        [3],
        [5],
        [7],
        [9]]) torch.Size([10, 1])


In [35]:
a

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

In [34]:
# view함수에는 inplace명령이 구현되어 있지 않다.
print(a.view_())

AttributeError: 'Tensor' object has no attribute 'view_'

#### 형상 연산 중 유용한 것

In [43]:
a = torch.arange(10).view(5,2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [37]:
b = torch.arange(10).view(2, 5)
b

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [44]:
print(a.view_as(b))
print(a.reshape_as(b))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### indexing, slicing

In [45]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [46]:
a[0]

tensor([0, 1])

In [47]:
a[0, 1]

tensor(1)

In [48]:
a[4, 1]

tensor(9)

In [49]:
a[:2]

tensor([[0, 1],
        [2, 3]])

### **텐서를 나누거나 두 개 이상의 텐서를 합치는 명령**

#### 나누는 연산

In [50]:
c = torch.rand(3, 6)
c

tensor([[0.9898, 0.6900, 0.7724, 0.5624, 0.3722, 0.3697],
        [0.6564, 0.1302, 0.9687, 0.8253, 0.2756, 0.0229],
        [0.3515, 0.0055, 0.6368, 0.5179, 0.8232, 0.7347]])

In [51]:
c1, c2, c3 = torch.chunk(c, 3, dim=1) #--> 3개로 나눈다.
print(c1)
print(c2)
print(c3)

tensor([[0.9898, 0.6900],
        [0.6564, 0.1302],
        [0.3515, 0.0055]])
tensor([[0.7724, 0.5624],
        [0.9687, 0.8253],
        [0.6368, 0.5179]])
tensor([[0.3722, 0.3697],
        [0.2756, 0.0229],
        [0.8232, 0.7347]])


In [52]:
c1, c2, c3 = torch.chunk(c, 3, dim=0)
print(c1)
print(c2)
print(c3)

tensor([[0.9898, 0.6900, 0.7724, 0.5624, 0.3722, 0.3697]])
tensor([[0.6564, 0.1302, 0.9687, 0.8253, 0.2756, 0.0229]])
tensor([[0.3515, 0.0055, 0.6368, 0.5179, 0.8232, 0.7347]])


In [53]:
torch.split(c, 1, dim=0) #--> axis=0에서 1개씩 나눈다.

(tensor([[0.9898, 0.6900, 0.7724, 0.5624, 0.3722, 0.3697]]),
 tensor([[0.6564, 0.1302, 0.9687, 0.8253, 0.2756, 0.0229]]),
 tensor([[0.3515, 0.0055, 0.6368, 0.5179, 0.8232, 0.7347]]))

In [54]:
torch.split(c, 2, dim=1) #--> axis=1에서 2개씩 나눈다.

(tensor([[0.9898, 0.6900],
         [0.6564, 0.1302],
         [0.3515, 0.0055]]),
 tensor([[0.7724, 0.5624],
         [0.9687, 0.8253],
         [0.6368, 0.5179]]),
 tensor([[0.3722, 0.3697],
         [0.2756, 0.0229],
         [0.8232, 0.7347]]))

In [55]:
torch.split(c, 3, dim=1) #--> axis=1에서 3개씩 나눈다.

(tensor([[0.9898, 0.6900, 0.7724],
         [0.6564, 0.1302, 0.9687],
         [0.3515, 0.0055, 0.6368]]),
 tensor([[0.5624, 0.3722, 0.3697],
         [0.8253, 0.2756, 0.0229],
         [0.5179, 0.8232, 0.7347]]))

#### 결합하는 연산

In [56]:
a = torch.ones(2, 3)
b = torch.zeros(3, 3)
a, b

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [57]:
torch.cat([a, b], dim=0)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [58]:
torch.cat([a, b], dim=1)

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 3 for tensor number 1 in the list.

In [59]:
a = torch.ones_like(b)
a, a.size()

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([3, 3]))

In [60]:
b, b.size()

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([3, 3]))

In [61]:
torch.stack([a, b], dim=1), torch.stack([a, b], dim=1).size()

(tensor([[[1., 1., 1.],
          [0., 0., 0.]],
 
         [[1., 1., 1.],
          [0., 0., 0.]],
 
         [[1., 1., 1.],
          [0., 0., 0.]]]),
 torch.Size([3, 2, 3]))

In [62]:
torch.stack([a, b], dim=0), torch.stack([a, b], dim=0).size()

(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]),
 torch.Size([2, 3, 3]))

In [63]:
torch.stack([a, b], dim=2), torch.stack([a, b], dim=2).size()

(tensor([[[1., 0.],
          [1., 0.],
          [1., 0.]],
 
         [[1., 0.],
          [1., 0.],
          [1., 0.]],
 
         [[1., 0.],
          [1., 0.],
          [1., 0.]]]),
 torch.Size([3, 3, 2]))

In [64]:
torch.tile(a, (3, 1))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [65]:
torch.tile(a, (1, 2))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
torch.vstack

<function _VariableFunctionsClass.vstack>

In [ ]:
torch.hstack

<function _VariableFunctionsClass.hstack>