<a href="https://colab.research.google.com/github/ElaYJ/Study_Deep_Learning/blob/main/Framework/PyTorch/21_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch 선형 회귀 구현

In [1]:
import pandas as pd
import numpy as np
import torch

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
torch.manual_seed(7777)

In [6]:
# from sklearn.datasets import load_boston
# boston = load_boston()
# df = pd.DataFrame(boston.data, columns=boston.feature_names)

url ='https://raw.githubusercontent.com/PinkWink/ML_tutorial/master/dataset/boston.csv'
df = pd.read_csv(url)
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [9]:
df_target = df.iloc[:, -1:]
df_target

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [10]:
df = df.iloc[:, :-1]
df['const'] = np.ones(df.shape[0])
df.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  const  
501     21.0  391.99   9.67    1.0  
502     21.0  396.90   9.08    1.0  
503     21.0  396.90   5.64    1.0  
504     21.0  393.45   6.48    1.0  
505     21.0  396.90   7.88    1.0

In [11]:
n, m = df.shape
n, m

(506, 14)

In [13]:
x = torch.tensor(df.values)
y = torch.tensor(df_target.values).view(-1, 1)
x.shape, y.shape

(torch.Size([506, 14]), torch.Size([506, 1]))

In [14]:
XT = torch.transpose(x, 0, 1)
XT.shape

torch.Size([14, 506])

In [15]:
w = torch.matmul(torch.matmul(torch.inverse(torch.matmul(XT, x)), XT), y)
w

tensor([[-1.0801e-01],
        [ 4.6420e-02],
        [ 2.0559e-02],
        [ 2.6867e+00],
        [-1.7767e+01],
        [ 3.8099e+00],
        [ 6.9222e-04],
        [-1.4756e+00],
        [ 3.0605e-01],
        [-1.2335e-02],
        [-9.5275e-01],
        [ 9.3117e-03],
        [-5.2476e-01],
        [ 3.6459e+01]], dtype=torch.float64)

In [16]:
w = torch.mm(torch.mm(torch.linalg.inv(torch.mm(XT, x)), XT), y)
w

tensor([[-1.0801e-01],
        [ 4.6420e-02],
        [ 2.0559e-02],
        [ 2.6867e+00],
        [-1.7767e+01],
        [ 3.8099e+00],
        [ 6.9222e-04],
        [-1.4756e+00],
        [ 3.0605e-01],
        [-1.2335e-02],
        [-9.5275e-01],
        [ 9.3117e-03],
        [-5.2476e-01],
        [ 3.6459e+01]], dtype=torch.float64)

In [17]:
torch.matmul(x, w)

tensor([[30.0038],
        [25.0256],
        [30.5676],
        [28.6070],
        [27.9435],
        [25.2563],
        [23.0018],
        [19.5360],
        [11.5236],
        [18.9203],
        [18.9995],
        [21.5868],
        [20.9065],
        [19.5529],
        [19.2835],
        [19.2975],
        [20.5275],
        [16.9114],
        [16.1780],
        [18.4061],
        [12.5239],
        [17.6710],
        [15.8329],
        [13.8063],
        [15.6783],
        [13.3867],
        [15.4640],
        [14.7085],
        [19.5474],
        [20.8764],
        [11.4551],
        [18.0592],
        [ 8.8111],
        [14.2828],
        [13.7068],
        [23.8146],
        [22.3419],
        [23.1089],
        [22.9150],
        [31.3576],
        [34.2151],
        [28.0206],
        [25.2039],
        [24.6098],
        [22.9415],
        [22.0967],
        [20.4232],
        [18.0366],
        [ 9.1066],
        [17.2061],
        [21.2815],
        [23.9722],
        [27.

In [21]:
y_pred = torch.matmul(x, w)

print("예측한 집값 :", y_pred[19], "실제 집값 :", df_target.values[19])

예측한 집값 : tensor([18.4061], dtype=torch.float64) 실제 집값 : [18.2]


#### Gradient descent 방식

In [22]:
w = torch.rand((14, 1), dtype=torch.float64, requires_grad=True)
b = torch.rand((1, 1),  dtype=torch.float64, requires_grad=True)

In [23]:
z = x.matmul(w) + b
loss = torch.mean((z - y)**2)

In [24]:
w.grad, b.grad

(None, None)

In [25]:
loss.backward()

In [26]:
w.grad, b.grad

(tensor([[4.6543e+03],
         [1.1592e+04],
         [1.2824e+04],
         [7.4684e+01],
         [6.1311e+02],
         [6.7807e+03],
         [7.6970e+04],
         [3.9565e+03],
         [1.1487e+04],
         [4.6771e+05],
         [2.0181e+04],
         [3.9043e+05],
         [1.4341e+04],
         [1.0850e+03]], dtype=torch.float64),
 tensor([[1084.9567]], dtype=torch.float64))

In [27]:
print(loss)

tensor(303557.1678, dtype=torch.float64, grad_fn=<MeanBackward0>)


In [30]:
loss.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [28]:
loss.detach().numpy()

array(303557.16782532)

In [29]:
with torch.no_grad():
    print(loss.numpy())

303557.16782532405


In [31]:
loss.item()

303557.16782532405

#### assign 대신에 data에 접근해서 값을 수정

tensor.data = 다른데이터

In [32]:
w

tensor([[0.9625],
        [0.8798],
        [0.6916],
        [0.0976],
        [0.5441],
        [0.6069],
        [0.7656],
        [0.2674],
        [0.7172],
        [0.4656],
        [0.7843],
        [0.7482],
        [0.5919],
        [0.0070]], dtype=torch.float64, requires_grad=True)

In [33]:
w.data

tensor([[0.9625],
        [0.8798],
        [0.6916],
        [0.0976],
        [0.5441],
        [0.6069],
        [0.7656],
        [0.2674],
        [0.7172],
        [0.4656],
        [0.7843],
        [0.7482],
        [0.5919],
        [0.0070]], dtype=torch.float64)

In [34]:
from IPython.display import display, clear_output

In [35]:
learning_rate = 3e-7

for epoch in range(100):
    z = x.matmul(w) + b
    loss = torch.mean((y - z)**2)
    loss.backward()
    w.data -= learning_rate * w.grad
    b.data -= learning_rate * b.grad

    # print("{:3} - loss : {}".format(epoch, loss.item()), end="\r")
    display("{:3} - loss : {}".format(epoch, loss.item()))
    clear_output(wait=True)

    # 이전 값을 누적하지 않도록 초기화 필요
    w.grad.zero_()
    b.grad.zero_()

' 99 - loss : 567.5846153430994'

In [36]:
learning_rate = 0.000003

for epoch in range(100):
    z = (x.matmul(w) + b)
    loss = torch.mean((z - y)**2)

    grads = torch.autograd.grad(loss, [w, b])
    w.data -= grads[0] * learning_rate
    b.data -= grads[1] * learning_rate

    # print("{:3} - loss : {}".format(epoch, loss.item()), end="\r")
    display("{:3} - loss : {}".format(epoch, loss.item()))
    clear_output(wait=True)

' 99 - loss : 389.61181393115777'

#### optimizer 사용하기

In [37]:
opt = torch.optim.SGD([w, b], lr=learning_rate)
# [w, b] : 미분값을 추적할 파라미터들

In [39]:
for epoch in range(100):
    z = (x.matmul(w) + b)
    loss = torch.mean((z - y)**2)

    loss.backward()
    opt.step()
    # print("{:3} - loss : {}".format(epoch, loss.item()), end="\r")
    display("{:3} - loss : {}".format(epoch, loss.item()))
    clear_output(wait=True)

    opt.zero_grad()

' 99 - loss : 258.18631163839325'

In [40]:
y_pred = x.matmul(w) + b
print("예측한 집값 :", y_pred[19].item(), "실제 집값 :", df_target.values[19])

예측한 집값 : 21.3181112540882 실제 집값 : [18.2]
