<a href="https://colab.research.google.com/github/ElaYJ/Study_Deep_Learning/blob/main/Lecture/16_TFKeras_Simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# time stamp data를 임의로 생성

X = []; Y = [];

for i in range(6): #--> 6개 sample 생성
    lst = list(range(i, i+4))
    X.append(list(map(lambda c: [c/10], lst)))
    Y.append((i+4)/10)

X = np.array(X)
Y = np.array(Y)
for i in range(len(X)):
    print(X[i], Y[i])

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9


In [3]:
# simple RNN 모델 구성

model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)
])
# units=10: simple RNN cell 10개, units는 SimpleRNN 레이어에 존재하는 뉴런의 수이다.
# return_sequences=False: 모든 셀 출력을 받지 X, return_sequences는 출력으로 시퀀스 전체를 출력할지 여부이다.
# input_shape=[4,1]이라는 것은 (timesteps=4, input_dim=1)이라는 것을 의미한다.

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 10)                120       
                                                                 
 dense (Dense)               (None, 1)                 11        
                                                                 
Total params: 131 (524.00 Byte)
Trainable params: 131 (524.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


- 모델을 그려보면

    <img src="https://github.com/ElaYJ/supplement/assets/153154981/3154e5ea-87e7-4c11-8a17-165c8e270704" width="57%">

In [6]:
print(model.layers[0].input_shape)
# The input layer expects a 3-dimensional input with the shape (batch_size, timesteps, input_dim)
# None은 배치 크기를 고정된 크기가 아닌 유동적인 크기로 처리하기 위한 것이다.

(None, 4, 1)


In [4]:
# 학습

model.fit(X, Y, epochs=100, verbose=0)

In [5]:
# 예측 결과 확인
# 허접하지만 노력은 했다.ㅋ

model.predict(np.array([[[0.6],[0.7],[0.8],[0.9]]]))

1/1 [==============================] - 0s 214ms/step


array([[0.92628056]], dtype=float32)

In [7]:
model.predict(np.array([[[-0.1],[0.1],[0.1],[0.2]]]))

1/1 [==============================] - 0s 25ms/step


array([[0.26968452]], dtype=float32)

In [8]:
# 모델을 좀 더 복잡하게 구성

model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=10, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=10, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 4, 10)             120       
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 4, 10)             210       
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 4, 10)             210       
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 10)                210       
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 761 (2.97 KB)
Trainable params: 761 (2.97 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
# 다시 훈련

model.fit(X, Y, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 3s 3s/step - loss: 0.9361
Epoch 2/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6899
Epoch 3/100
1/1 [==============================] - 0s 13ms/step - loss: 0.4821
Epoch 4/100
1/1 [==============================] - 0s 26ms/step - loss: 0.3153
Epoch 5/100
1/1 [==============================] - 0s 14ms/step - loss: 0.1892
Epoch 6/100
1/1 [==============================] - 0s 15ms/step - loss: 0.1007
Epoch 7/100
1/1 [==============================] - 0s 13ms/step - loss: 0.0446
Epoch 8/100
1/1 [==============================] - 0s 16ms/step - loss: 0.0144
Epoch 9/100
1/1 [==============================] - 0s 15ms/step - loss: 0.0034
Epoch 10/100
1/1 [==============================] - 0s 15ms/step - loss: 0.0053
Epoch 11/100
1/1 [==============================] - 0s 18ms/step - loss: 0.0148
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 0.0273
Epoch 13/100
1/1 [==============================] -

In [10]:
# 예측 결과 확인

model.predict(np.array([[[0.6],[0.7],[0.8],[0.9]]]))

1/1 [==============================] - 1s 629ms/step


array([[0.87919164]], dtype=float32)