<a href="https://colab.research.google.com/github/ElaYJ/Study_Deep_Learning/blob/main/DL_Framework/TensorFlow/03_Tensor_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor 연산

In [2]:
import tensorflow as tf

tf.__version__

'2.15.0'

아래의 기본 연산은 특수 메서드를 이용하여 연산자 오버로딩이 되어 있으므로 그냥 연산자 기호를 사용하는게 가능!

* `tf.add`: 덧셈
* `tf.subtract`: 뺄셈
* `tf.multiply`: 곱셈
* `tf.divide`: 나눗셈
* `tf.pow`: n-제곱
* `tf.negative`: 음수 부호


In [3]:
a = tf.range(6, dtype=tf.int32)
b = 2 * tf.ones(6, dtype=tf.int32)

tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

In [4]:
a + b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

**여러가지 연산**

* `tf.abs`: 절대값
* `tf.sign`: 부호
* `tf.round`: 반올림
* `tf.ceil`: 올림
* `tf.floor`: 내림
* `tf.square`: 제곱
* `tf.sqrt`: 제곱근
* `tf.maximum`: 두 텐서의 각 원소에서 최댓값만 반환.
* `tf.minimum`: 두 텐서의 각 원소에서 최솟값만 반환.
* `tf.cumsum`: 누적합
* `tf.cumprod`: 누적곱


In [5]:
tf.maximum(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5], dtype=int32)>

### Axis 이해하기

In [6]:
rank_2 = tf.random.normal((3, 3))

In [7]:
rank_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.1956068 , -1.6649842 , -0.6412402 ],
       [-0.19667937, -0.96673244,  0.7879124 ],
       [ 1.2113066 ,  0.57480496,  0.8116904 ]], dtype=float32)>

In [8]:
# 중앙의 값

rank_2[1,1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.96673244>

In [9]:
rank_2[0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.1956068, -1.6649842, -0.6412402], dtype=float32)>

In [10]:
rank_2[0, 0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.1956068>

In [11]:
rank_3 = tf.random.normal((3, 3, 3))

In [12]:
rank_3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 0.29864508,  0.60712355,  0.4981782 ],
        [ 0.35562587,  1.216464  , -0.7182583 ],
        [-0.08345941, -1.908295  ,  0.47373652]],

       [[ 1.6115022 ,  0.30214235,  0.8587347 ],
        [-1.1377591 , -0.08054514, -1.4224585 ],
        [-0.6209164 , -0.62983066,  1.1635516 ]],

       [[-0.07982248, -0.23376386,  0.60522807],
        [-1.1477547 ,  0.24908201,  0.27922326],
        [ 0.17970449,  0.41293985,  0.17307945]]], dtype=float32)>

In [14]:
rank_3[1,1,2]

<tf.Tensor: shape=(), dtype=float32, numpy=-1.4224585>

In [15]:
rank_4 = tf.random.normal((3, 3, 3, 3))

In [17]:
rank_4

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[-9.4028783e-01,  1.1796626e+00,  5.6787592e-01],
         [-1.5804422e+00,  4.2516384e-01,  3.4847394e-01],
         [ 1.8794473e-03, -2.1688492e+00, -5.8890474e-01]],

        [[ 8.7653905e-01,  1.6725610e+00, -6.3037103e-01],
         [ 4.9751621e-01,  5.7685125e-01, -1.1027012e+00],
         [-6.8535489e-01,  3.9131176e-01,  1.4030033e+00]],

        [[ 2.1948616e-01, -2.1615391e+00,  1.3711005e+00],
         [-1.5820038e+00,  8.5939240e-01,  8.9341587e-01],
         [ 6.1016190e-01,  1.8193495e-01, -1.6584094e-01]]],


       [[[-2.8843083e+00,  2.8983729e-02,  1.8595110e+00],
         [-2.8092906e-01, -3.6179480e-01, -1.1404532e+00],
         [-1.9250419e+00, -5.0496899e-02,  9.1224414e-01]],

        [[ 7.4830675e-01,  4.4694149e-01, -2.1010247e-01],
         [-9.8911834e-01,  1.3127847e+00,  8.9708668e-01],
         [ 1.8584548e+00, -9.7564012e-01,  1.0600127e+00]],

        [[ 6.7520939e-02, -1.1852282e+00, -1.4062

In [16]:
rank_4[1,2,1,2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.6959619>

### **차원 축소 연산**

* `tf.reduce_mean`: 설정한 축의 평균을 구한다.
* `tf.reduce_max`: 설정한 축의 최댓값을 구한다.
* `tf.reduce_min`: 설정한 축의 최솟값을 구한다.
* `tf.reduce_prod`: 설정한 축의 요소를 모두 곱한 값을 구한다.
* `tf.reduce_sum`: 설정한 축의 요소를 모두 더한 값을 구한다.

In [18]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>

In [19]:
tf.reduce_sum(a, axis=0),

(<tf.Tensor: shape=(), dtype=int32, numpy=15>,)

In [20]:
# 차원을 유지하고 싶다면...

tf.reduce_sum(a, axis=0, keepdims=True)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([15], dtype=int32)>

In [21]:
b = tf.random.normal((2,7))
b

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[ 1.1079564 , -0.28696337,  0.13386111,  2.2797525 ,  0.05958601,
         1.1391575 ,  1.4547833 ],
       [ 0.308695  ,  0.18551877,  1.5702655 , -0.1896621 ,  0.4386407 ,
        -1.359739  , -1.0493965 ]], dtype=float32)>

In [22]:
tf.reduce_mean(b, axis=0)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([ 0.7083257 , -0.0507223 ,  0.8520633 ,  1.0450451 ,  0.24911337,
       -0.11029071,  0.2026934 ], dtype=float32)>

In [23]:
tf.reduce_mean(b, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.841162  , -0.01366821], dtype=float32)>

In [24]:
c = tf.random.normal((2, 4, 3))
c

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.02705411, -0.1338259 , -0.28384113],
        [ 2.0626218 ,  0.8332451 ,  0.19649807],
        [-0.1080901 ,  0.2949258 , -1.9695839 ],
        [ 0.93423873, -2.519091  ,  2.6448328 ]],

       [[-0.25945604,  0.29232675, -0.6237756 ],
        [-0.4349887 ,  2.0240366 ,  0.92180014],
        [ 1.2656821 , -1.7330259 ,  0.29808694],
        [-0.04835184, -1.1604881 ,  0.0819112 ]]], dtype=float32)>

In [25]:
tf.reduce_mean(c, axis=0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.11620096,  0.07925043, -0.45380837],
       [ 0.81381655,  1.4286408 ,  0.5591491 ],
       [ 0.578796  , -0.71905005, -0.83574843],
       [ 0.44294345, -1.8397895 ,  1.363372  ]], dtype=float32)>

In [26]:
tf.reduce_mean(c, axis=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.72895616, -0.3811865 ,  0.14697647],
       [ 0.13072138, -0.14428768,  0.16950567]], dtype=float32)>

In [27]:
tf.reduce_mean(c, axis=2)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.1302043 ,  1.0307883 , -0.5942494 ,  0.3533269 ],
       [-0.1969683 ,  0.83694935, -0.05641896, -0.37564293]],
      dtype=float32)>

### 행렬 연산

행렬과 관련된 연산

* `tf.matmul`: 내적
* `tf.linalg.inv`: 역행렬


In [28]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [1., 1.]], dtype=float32)>

In [29]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)>

### 차원 변경

**크기 및 차원을 바꾸는 명령**
 (잘 사용됩니다!!)

이를 사용 할 때는 축을 잘 이해하고 사용하시면 좋습니다.

* `tf.reshape`: 벡터 행렬의 크기 변환
* `tf.transpose`: 전치 연산
* `tf.expand_dims`: 지정한 축으로 차원을 추가 $~\dashrightarrow~$ 데이터를 한 묶음으로 묶을 때 사용됨
* `tf.squeeze`: 벡터로 차원을 축소

In [30]:
a = tf.range(6, dtype=tf.int32) #--> [0, 1, 2, 3, 4, 5]
print("a     :", a, "\n")

# reshape
# 1차원 벡터는 2x3 크기의 2차원 행렬로 변환
a_2d = tf.reshape(a, (2, 3))
print("a_2d  :", a_2d, "\n")

# transpose
# 2x3 크기의 2차원 행렬을 3x2 크기의 2차원 행렬로 변환
a_2d_t = tf.transpose(a_2d)
print("a_2d_t:", a_2d_t, "\n")

# expand_dims
# 2x3 크기의 2차원 행렬을 1x2x3 크기의 3차원 행렬로 변환
a_3d = tf.expand_dims(a_2d, 0) #--> 0번 axis에 차원 추가
print("a_3d  :", a_3d, "\n")

# 1x2x3 크기의 3차원 행렬을 1x2x3x1 크기의 4차원 행렬로 변환
a_4d = tf.expand_dims(a_3d, 3) #--> 3번 axis에 차원 추가, 3대신 -1로 써도 됨.
print("a_4d  :", a_4d, "\n")

# squeeze
# 1x2x3x1 크기의 4차원 행렬을 1차원 벡터로 변환
a_1d = tf.squeeze(a_4d)
print("a_1d  :", a_1d, "\n")

a     : tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32) 

a_2d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 

a_2d_t: tf.Tensor(
[[0 3]
 [1 4]
 [2 5]], shape=(3, 2), dtype=int32) 

a_3d  : tf.Tensor(
[[[0 1 2]
  [3 4 5]]], shape=(1, 2, 3), dtype=int32) 

a_4d  : tf.Tensor(
[[[[0]
   [1]
   [2]]

  [[3]
   [4]
   [5]]]], shape=(1, 2, 3, 1), dtype=int32) 

a_1d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 



In [31]:
tf.squeeze(a_4d, axis=0)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]], dtype=int32)>

In [32]:
# shape=1 일 때만 squeeze() 적용 가능
# a_4d의 axis=2의 shape=3이므로 에러 발생

tf.squeeze(a_4d, axis=2)

InvalidArgumentError: {{function_node __wrapped__Squeeze_device_/job:localhost/replica:0/task:0/device:CPU:0}} Can not squeeze dim[2], expected a dimension of 1, got 3 [Op:Squeeze] name: 

### Tensor 나누기/합치기

**텐서를 나누거나 두 개 이상의 텐서를 합치는 명령**

* `tf.slice`: 특정 부분을 추출
* `tf.split`: 분할
* `tf.concat`: 합치기
* `tf.tile`: 복제-붙이기
* `tf.stack`: 합성
* `tf.unstack`: 분리

In [33]:
a = tf.reshape(tf.range(12), (3, 4))
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [34]:
tf.slice(a, begin=[0, 1], size=[2, 3]) #--> (0, 1)위치에서 (2개 rows, 3개 cols)만큼 뽑아낸다.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>

In [35]:
a1, a2 = tf.split(a, num_or_size_splits=2, axis=1)  # 세로축(axis=1)을 따라 2개로 분할
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [36]:
tf.concat([a1, a2], axis=1) # 세로축(axis=1)을 따라 a1, a2를 합치기

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [37]:
tf.concat([a1, a2], axis=0)

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]], dtype=int32)>

In [38]:
a1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [4, 5],
       [8, 9]], dtype=int32)>

In [39]:
tf.tile(a1, [1, 3])  # (axis=1)을 따라 3개로 복사-붙이기

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]], dtype=int32)>

In [41]:
a3 = tf.stack([a1, a2])  # 3x2 행렬 a1, a2를 추가적인 차원으로 붙여서 2x3x2 고차원 텐서 생성
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]], dtype=int32)>

In [42]:
tf.unstack(a3, axis=1)
# 2x3x2 고차원 텐서에서 axis=1에 해당하는 3을 0차원으로 풀어서 3개의 2x2 행렬 생성

[<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 8,  9],
        [10, 11]], dtype=int32)>]

### 간단 퀴즈

다음 코드를 에러 없이 실행하라.

In [45]:
a = tf.constant(((1, 2, 3), (1, 2, 3)))
b = tf.constant([1, 2, 3])

# tf.matmul(a, b)

-----

In [46]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [47]:
tf.expand_dims(b, axis=1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [48]:
tf.matmul(a, tf.expand_dims(b, axis=1))

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14],
       [14]], dtype=int32)>