<a href="https://colab.research.google.com/github/ElaYJ/Study_Deep_Learning/blob/main/DL_Framework/TensorFlow/06_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 퍼셉트론

In [1]:
import tensorflow as tf
import numpy as np

- 이번엔 Iris 데이터 중 두 종류를 분류하는 퍼셉트론을 제작한다.

- y값은 1 또는 -1을 사용하고 활성화 함수로는 하이퍼탄젠트(hypertangent)함수를 사용한다.

$$\Large{ \hat{y} = tanh(w^Tx) }$$

- 비용 함수로는 다음 식을 사용한다.

$$
\large{
Loss = \sum_{i=1}^N \max(0, -y_i \hat{y_i})
}
$$

- $\,y_i\,$와 $~\hat y_i\,$의 값이 같으면 -1로 max 값이 0이 되므로 counting에서 제외됨.

- $\,y_i\,$와 $~\hat y_i$ 두 값이 다를 때, 즉 예측값이 얼마나 틀렸는지를 손실함수로 사용

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

- IRIS type 2종류만 사용

- features도 sepal length, sepal width 2개만 사용

In [3]:
idx = np.in1d(iris.target, [0, 2])
X_data = iris.data[idx, 0:2]
y_data = (iris.target[idx] - 1.0)[:, np.newaxis]

In [4]:
X_data.shape, y_data.shape

((100, 2), (100, 1))

In [5]:
X_data[0].shape, X_data[0:1].shape

((2,), (1, 2))

In [6]:
X_data[0], X_data[0:1]

(array([5.1, 3.5]), array([[5.1, 3.5]]))

In [7]:
idx

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [8]:
(iris.target[idx] - 1.0)

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
(iris.target[idx] - 1.0)[:, np.newaxis]

array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

### Perceptron 구현

- 다음 데이터를 이용해 Perceptron을 구현해 본다.

    - 데이터 하나당 한번씩 weights 업데이트
    - step size == 0.0003
    - iteration == 200

In [10]:
num_iter = 500
lr = 0.0003

In [11]:
w = tf.Variable(tf.random.normal([2, 1], dtype=tf.float64))
b = tf.Variable(tf.random.normal([1, 1], dtype=tf.float64))

In [28]:
zero = tf.constant(0, dtype=tf.float64)

for i in range(num_iter):
    for i in range(X_data.shape[0]):
        x = X_data[i:i+1] #--> 차원 유지를 위해 [i:i+1]사용
        y = y_data[i:i+1]

        with tf.GradientTape() as tape:
            logit = tf.matmul(x, w) + b
            y_hat = tf.tanh(logit)
            loss = tf.maximum(zero, tf.multiply(-y, y_hat))

        grad = tape.gradient(loss, [w, b])
        w.assign_add(-lr * grad[0])
        b.assign_add(-lr * grad[1])
        # w.assign_sub(lr * grad[0])
        # b.assign_sub(lr * grad[1])
        # 이거 쓰면 accuracy가 엉망으로 나옴. Why?

In [29]:
y_pred = tf.tanh(tf.matmul(X_data, w) + b)

In [30]:
y_pred[:50]

<tf.Tensor: shape=(50, 1), dtype=float64, numpy=
array([[-0.07074017],
       [-0.0074678 ],
       [-0.04845832],
       [-0.03915647],
       [-0.09111927],
       [-0.11324705],
       [-0.08373098],
       [-0.06146116],
       [-0.020534  ],
       [-0.02238119],
       [-0.08370463],
       [-0.07260512],
       [-0.01306438],
       [-0.04102803],
       [-0.105865  ],
       [-0.16986567],
       [-0.11324705],
       [-0.07074017],
       [-0.0818429 ],
       [-0.11509719],
       [-0.03912997],
       [-0.10035359],
       [-0.11327325],
       [-0.04100154],
       [-0.07260512],
       [-0.00187074],
       [-0.06146116],
       [-0.06516885],
       [-0.05030185],
       [-0.04845832],
       [-0.02797482],
       [-0.03912997],
       [-0.15353942],
       [-0.15170851],
       [-0.02238119],
       [-0.03169412],
       [-0.04843185],
       [-0.0966671 ],
       [-0.03543904],
       [-0.05588325],
       [-0.07630709],
       [ 0.0744244 ],
       [-0.06519527],
     

In [31]:
print("예측치 :", y_pred[0].numpy(),  "정답 :", y_data[0])
print("예측치 :", y_pred[23].numpy(), "정답 :", y_data[23])
print("예측치 :", y_pred[87].numpy(), "정답 :", y_data[87])

예측치 : [-0.07074017] 정답 : [-1.]
예측치 : [-0.04100154] 정답 : [-1.]
예측치 : [0.06149523] 정답 : [1.]


In [32]:
print("예측치 :", -1 if y_pred[0] < 0 else 1,  "정답 :", y_data[0])
print("예측치 :", -1 if y_pred[51] < 0 else 1, "정답 :", y_data[51])
print("예측치 :", -1 if y_pred[88] < 0 else 1, "정답 :", y_data[88])

예측치 : -1 정답 : [-1.]
예측치 : 1 정답 : [1.]
예측치 : 1 정답 : [1.]


In [33]:
wrong = 0

for i in range(len(y_data)):
    y_hat = 1. if y_pred[i] > 0 else -1.
    if y_hat != y_data[i][0]:
        wrong += 1

accuracy = wrong/len(y_data) * 100
accuracy

1.0